### PR TITLE
Adapting the plugin for Xcode 5 (using "Source Control" menu)

### PR DESCRIPTION
**Pull request by mabedan**

### CODE REVIEW

**Comment by noahemmet** [comment]
+1

**Comment by nickkjordan** [comment]
I don't think a message popup is the way to go, rather than just to document it on the readme.  As a new user, I had trouble finding it and immediately went to the docs to no avail.

**Comment by larsxschneider** [comment]
@nickkjordan  What do you mean by "it" with "As a new user, I had trouble finding it" ? Thanks!

**Comment by nickkjordan** [comment]
Sorry, I meant I had trouble finding the additional "Github" tab on the menu bar.

**Comment by cbowns** [comment]
I'm maintaining my fork at https://github.com/cbowns/ShowInGitHub with this PR landed.

Also, please merge this!

**Comment by larsxschneider** [comment]
Alright. Let's see how this goes. Thanks a lot @mabedan !!

**Pull request merged**
