### PR TITLE
Add "Open Pull Request on GitHub" feature

### PR DESCRIPTION
**Pull request by morishin**
### Done
- Merge djromero/master (for Xcode 7.1 support)
- Add "Oper Pull Request on GitHub" feature
- Update README

Please review&merge if you like this feature. @larsxschneider 
@djromero FYI

### CODE REVIEW

**Comment by larsxschneider** [comment]
Thanks for the PR! Lots of code! I need some time to review!

**Comment by zenangst** [comment]
**Bump** ^^

**Comment by larsxschneider** [comment]
got it :smile: !

**Comment by morishin** [comment]
I rebased branch to resolve conflict :)

**Pull request closed without merging**
